export type Problem = {
	id: string;
	title: string;
	difficulty: string;
	category: string;
	order: number;
	videoId?: string;
  };
  
  export const problems: Problem[] = [
	{
	  id: "quadratic-equations",
	  title: "Solving Quadratic Equations",
	  difficulty: "Easy",
	  category: "Algebra 2",
	  order: 1,
	  videoId: "",
	},
	{
	  id: "logarithmic-functions",
	  title: "Logarithmic Functions",
	  difficulty: "Medium",
	  category: "Algebra 2",
	  order: 2,
	  videoId: "",
	},
	{
	  id: "rational-expressions",
	  title: "Simplifying Rational Expressions",
	  difficulty: "Hard",
	  category: "Algebra 2",
	  order: 3,
	  videoId: "",
	},
	{
	  id: "polynomial-division",
	  title: "Polynomial Division",
	  difficulty: "Easy",
	  category: "Algebra 2",
	  order: 4,
	  videoId: "",
	},
	{
	  id: "exponential-growth",
	  title: "Exponential Growth",
	  difficulty: "Medium",
	  category: "Algebra 2",
	  order: 5,
	  videoId: "",
	},
	{
	  id: "conic-sections",
	  title: "Analyzing Conic Sections",
	  difficulty: "Hard",
	  category: "Algebra 2",
	  order: 6,
	  videoId: "",
	},
	{
	  id: "trig-identities",
	  title: "Basic Trigonometric Identities",
	  difficulty: "Easy",
	  category: "Trigonometry",
	  order: 7,
	  videoId: "",
	},
	{
	  id: "trig-equations",
	  title: "Solving Trigonometric Equations",
	  difficulty: "Medium",
	  category: "Trigonometry",
	  order: 8,
	  videoId: "",
	},
	{
	  id: "law-of-sines",
	  title: "Law of Sines",
	  difficulty: "Hard",
	  category: "Trigonometry",
	  order: 9,
	  videoId: "",
	},
	{
	  id: "law-of-cosines",
	  title: "Law of Cosines",
	  difficulty: "Medium",
	  category: "Trigonometry",
	  order: 10,
	  videoId: "",
	},
	{
	  id: "unit-circle",
	  title: "Unit Circle",
	  difficulty: "Easy",
	  category: "Trigonometry",
	  order: 11,
	  videoId: "",
	},
	{
	  id: "logarithmic-equations",
	  title: "Solving Logarithmic Equations",
	  difficulty: "Hard",
	  category: "Algebra 2",
	  order: 12,
	  videoId: "",
	},
	{
	  id: "parabolas",
	  title: "Graphing Parabolas",
	  difficulty: "Easy",
	  category: "Algebra 2",
	  order: 13,
	  videoId: "",
	},
	{
	  id: "complex-numbers",
	  title: "Complex Numbers",
	  difficulty: "Medium",
	  category: "Algebra 2",
	  order: 14,
	  videoId: "",
	},
	{
	  id: "sequences-and-series",
	  title: "Sequences and Series",
	  difficulty: "Medium",
	  category: "Algebra 2",
	  order: 15,
	  videoId: "",
	},
	{
	  id: "probability",
	  title: "Basic Probability",
	  difficulty: "Easy",
	  category: "Algebra 2",
	  order: 16,
	  videoId: "",
	},
	{
	  id: "matrix-multiplication",
	  title: "Matrix Multiplication",
	  difficulty: "Hard",
	  category: "Algebra 2",
	  order: 17,
	  videoId: "",
	},
	{
	  id: "sin-cos-tan",
	  title: "Understanding sin, cos, tan",
	  difficulty: "Easy",
	  category: "Trigonometry",
	  order: 18,
	  videoId: "",
	},
	{
	  id: "trig-functions",
	  title: "Graphing Trigonometric Functions",
	  difficulty: "Medium",
	  category: "Trigonometry",
	  order: 19,
	  videoId: "",
	},
	{
	  id: "trig-inverses",
	  title: "Inverse Trigonometric Functions",
	  difficulty: "Hard",
	  category: "Trigonometry",
	  order: 20,
	  videoId: "",
	}
  ];